common:
  save_csv: False
  ckpt_dir: "quantitative"
  seed: 123
  
dataset:
  common:
    sf: 2

  valid:
    type: ImagePairDataset
    hr_dir: /dataset/NTIRE2023/HR/valid/DIV2K/
    lr_dir:  /dataset/NTIRE2023/LR/x2/DIV2K/DIV2K_valid_LR_bicubic/X2/
    patch_size : -1
    batch_size: 1
    num_workers: 4

metrics: 
  types: [psnr_Y]