common:
  ckpt_dir: "quantitative"
  seed: 123
  
dataset:
  common:
    sf: 2
    patch_size : -1

  valid:
    type: ImagePairDataset
    hr_dir: /dataset/SR/deg/HR
    lr_dir: /dataset/SR/deg/LR
    batch_size: 1
    num_workers: 4

metrics: 
  types: [psnr, ssim, lpips]