common:
  save_csv: False
  ckpt_dir: "quantitative"
  seed: 123
  
dataset:
  common:
    sf: 2

  valid:
    type: ImagePairDataset
    hr_dir: /workspace/pigmania/dataset/jaheoble/val/div2KRK/gt
    lr_dir: 
    patch_size : -1
    batch_size: 1
    num_workers: 4

metrics: 
  types: [psnr_Y]