common:
  ckpt_dir: "quantitative"
  seed: 123
  
dataset:
  common:
    sf: 2

  valid:
    type: ImagePairDataset
    hr_dir: /dataset/SR/DIV2KRK/gt/
    lr_dir: /dataset/SR/DIV2KRK/lr_x2/
    patch_size : -1
    batch_size: 1
    num_workers: 4

metrics: 
  types: [psnr, ssim, niqe]