common:
  save_csv: False
  ckpt_dir: "quantitative"
  seed: 123
  
dataset:
  common:
    sf: 2

  valid:
    type: ImagePairDataset
    hr_dir: /workspace/SR/SR-Trainer/testsets/Set5/HR
    lr_dir: /workspace/SR/SR-Trainer/testsets/Set5/LR
    patch_size : -1
    batch_size: 1
    num_workers: 4

metrics: 
  types: [psnr_Y]