name: RealESRGAN

generator:
  path: ""
  state_dict: ["g", "g_optim", "iteration"]
  scale: 4
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23
  num_grow_ch: 32

discriminator:
  path: ""
  state_dict: ["d", "d_optim", "iteration"]
  num_in_ch: 3
  num_feat: 64
  skip_connection: true