generator:
  name: RealESRGAN
  path: ""
  n_colors: 3
  scale: 4
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23
  num_grow_ch: 32

discriminator:
  name: UNet_Discriminator
  path: ""
  num_in_ch: 3
  num_feat: 64
  skip_connection: true