generator:
  name: SCUNet
  path: "/workspace/sr-trainer/model_zoo/SCUNET_STUDENT.pth"
  n_colors: 3
  scale: 2
  in_nc: 3
  config: [1, 1, 1, 1, 1, 1, 1]
  dim: 64
  head_dim: 32
  window_size: 8
  drop_path_rate: 0.0
  input_resolution: 256
  upsampler: "nearest+conv"

discriminator:
  name: UNet_Discriminator
  path: ""
  num_in_ch: 3
  num_feat: 64
  skip_connection: true

teacher:
  name: SCUNet
  path: ""
  n_colors: 3
  scale: 2
  in_nc: 3
  config: [4, 4, 4, 4, 4, 4, 4]
  dim: 64
  head_dim: 32
  window_size: 8
  drop_path_rate: 0.0
  input_resolution: 256
  upsampler: "nearest+conv"

student:
  name: SCUNet
  path: ""
  n_colors: 3
  scale: 2
  in_nc: 3
  config: [1, 1, 1, 1, 1, 1, 1]
  dim: 64
  head_dim: 32
  window_size: 8
  drop_path_rate: 0.0
  input_resolution: 256
  upsampler: "nearest+conv"