name: SwinIR

generator:
  path: ""
  state_dict: ["g", "g_optim", "iteration"]
  img_size: 64
  patch_size: 1
  in_chans: 3
  embed_dim: 60
  depths: [6, 6, 6, 6]
  num_heads: [6, 6, 6, 6]
  window_size: 8
  mlp_ratio: 2.0
  qkv_bias: true
  qk_scale: null
  drop_rate: 0.0
  attn_drop_rate: 0.0
  drop_path_rate: 0.1
  ape: false
  patch_norm: true
  use_checkpoint: false,
  scale: 1
  img_range: 1.0
  upsampler: ""
  resi_connection: "1conv"

discriminator:
  path: ""
  state_dict: ["d", "d_optim", "iteration"]
  num_in_ch: 3
  num_feat: 64
  skip_connection: true