common:
  iteration: 800001
  save_log_every: 100
  save_img_every: 1000
  save_model_every: 10000
  seed: 123
  use_wandb: false
  use_mlflow: true
  ckpt_dir: "gan_cpkt"
  save_img_dir: "images"
  method: GAN

mlflow:
  host: "127.0.0.1"
  port: "8080"
  experiment_name: "test"
  
ddp:
  distributed: false
  nodes: 1
  world_size: 1
  dist_url: "tcp://localhost:12355"
  dist_backend: "nccl"

loss:
  lists: ["MAE", "GANLoss", "PerceptualLoss"] #MAE
  GANLoss:
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 1e-1
  PerceptualLoss:
    vgg_path: /workspace/SuperResolution/model_zoo/VGG/vgg19-dcbb9e9d.pth # https://pytorch.org/vision/0.8/_modules/torchvision/models/vgg.html
    layer_weights:
      'conv1_2': 0.1
      'conv2_2': 0.1
      'conv3_4': 1
      'conv4_4': 1
      'conv5_4': 1
    vgg_type: vgg19
    use_input_norm: true,
    range_norm: false,
    perceptual_weight: !!float 1.0
    criterion: l1

optim:
  type: "Adam"
  Adam:
    lr: !!float 2e-4
    betas: [0.9, 0.999]
    weight_decay: 0

scheduler:
  type: MultiStepLR
  MultiStepLR:
    milestones: [400000]
    gamma: 0.5

metrics:
  types: [psnr, ssim, lpips]

defaults:
  - dataset/train/ImageDegradationDataset
  - dataset/valid/ImageDegradationDataset