common:
  iteration: 800001
  save_log_every: 100
  save_img_every: 1000
  save_model_every: 10000
  seed: 123
  use_wandb: true
  ckpt_dir: "kd_cpkt"
  save_img_dir: "images"
  method: KD

ddp:
  distributed: false
  nodes: 1
  world_size: 1
  dist_url: "tcp://localhost:12355"
  dist_backend: "nccl"

loss:
  lists: ["MAE", "Wavelet"] #MAE, "PerceptualLoss"
  WaveletLoss:
    type: 'db4'
    level: 3
    pad: 'zero'
    alpha: 0
  GANLoss:
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 1e-1
  PerceptualLoss:
    vgg_path: /workspace/SuperResolution/model_zoo/VGG/vgg19-dcbb9e9d.pth # https://pytorch.org/vision/0.8/_modules/torchvision/models/vgg.html
    layer_weights:
      'conv1_2': 0.1
      'conv2_2': 0.1
      'conv3_4': 1
      'conv4_4': 1
      'conv5_4': 1
    vgg_type: vgg19
    use_input_norm: true,
    range_norm: false,
    perceptual_weight: !!float 1.0
    criterion: l1

optim:
  type: "Adam"
  Adam:
    lr: !!float 1e-4
    betas: [0.9, 0.999]
    weight_decay: 0

scheduler:
  type: MultiStepLR
  MultiStepLR:
    milestones: [400000]
    gamma: 0.5

metrics:
  types: [psnr, ssim]

dataset:
  common:
    sf: -1
  valid:
    type: ImagePairDataset
    hr_dir: /dataset/SR/DIV2KRK/gt
    lr_dir: /dataset/SR/DIV2KRK/lr_x2
    patch_size : -1
    batch_size: 1
    num_workers: 2

  train:
    type: ImageDegradationDataset
    hr_dir: /dataset/SR/train
    lr_dir: ""
    gt_size: 320
    patch_size : 256
    batch_size: 16
    num_workers: 8

    ImageDegradationDataset: 
      sharpen:
        use: false
        weight: 1.0
        radius: 50
        threshold: 10
      
      deg:
        use: true
        plus: false
        processes : [
          # "blur_1",
          # "blur_2",
          "resize_1",
          "resize_2",
          "gaussian_noise_1",
          "poisson_noise_1",
          "sparkle_noise_1",
          "jpeg_noise_1"
        ]
        processes_plus : [
          "blur_1",
          "resize_1",
          "gaussian_noise_1",
          "poisson_noise_1",
          "sparkle_noise_1",
          "blur_2",
          "resize_2",
          "gaussian_noise_2",
          "poisson_noise_2",
          "sparkle_noise_2",
        ]
        jpeg_prob: 0.9
        shuffle_prob: 0.1
        updown_type: ["up", "down", "keep"]
        mode_list: ["area", "bilinear", "bicubic"]
        noise_level1: 2
        noise_level2: 25

        ### The first degradation process
        resize_prob: [0.2, 0.7, 0.1] 
        resize_range: [0.15, 1.5]
        gaussian_noise_prob: 0.5
        noise_range: [1, 30]
        poisson_scale_range: [0.05, 3]
        gray_noise_prob: 0.4
        jpeg_range: [30, 95]

        blur_kernel_size: 21
        kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
        kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
        sinc_prob: 0.1
        blur_sigma: [0.2, 3]
        betag_range: [0.5, 4]
        betap_range: [1, 2]

        ### The second degradation process
        second_blur_prob: 0.8
        resize_prob2: [0.3, 0.4, 0.3]  # up, down, keep
        resize_range2: [0.3, 1.2]
        gaussian_noise_prob2: 0.5
        noise_range2: [1, 25]
        poisson_scale_range2: [0.05, 2.5]
        gray_noise_prob2: 0.4
        jpeg_range2: [30, 95]

        blur_kernel_size2: 21
        kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
        kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
        sinc_prob2: 0.1
        blur_sigma2: [0.2, 1.5]
        betag_range2: [0.5, 4]
        betap_range2: [1, 2]

        final_sinc_prob: 0.8

        h_shift_strength: 2
        v_shift_strength: 1