common:
  iteration: 800001
  save_log_every: 100
  save_img_every: 1000
  save_model_every: 10000
  seed: 123
  use_wandb: false
  use_mlflow: true
  ckpt_dir: "psnr_cpkt"
  save_img_dir: "images"
  method: NET

mlflow:
  host: "127.0.0.1"
  port: "8080"
  experiment_name: "test"
  
ddp:
  distributed: false
  nodes: 1
  world_size: 1
  dist_url: "tcp://localhost:12355"
  dist_backend: "nccl"

loss:
  lists: ["MAE"]

optim:
  type: "Adam"
  Adam:
    lr: !!float 1e-4
    betas: [0.9, 0.999]
    weight_decay: 0

scheduler:
  type: MultiStepLR
  MultiStepLR:
    milestones: [400000]
    gamma: 0.5

metrics:
  types: [psnr]

defaults:
  - dataset/train/ImageDegradationDataset
  - dataset/valid/ImageDegradationDataset